apiVersion: v1
kind: Service
metadata:
  name: x-ray-sample-front-k8s
  labels:
    app: x-ray-sample-front-k8s

spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: x-ray-sample-front-k8s

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-ray-sample-front-k8s
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: x-ray-sample-front-k8s

  template:
    metadata:
      labels:
        app: x-ray-sample-front-k8s

    spec:
      containers:
        - name: x-ray-sample-front-k8s
          image: 040256855012.dkr.ecr.ap-southeast-1.amazonaws.com/test-app:v1.4
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          env:
            - name: EXPORTER_ENDPOINT
              value: aws-collector.aws-otel:4317
          ports:
            - containerPort: 8080
      serviceAccountName: ekstos3

